{
 "title": "Order Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Количество заказов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Количество" }
   ],
   "targets": [
    { "expr": "pvz_orders_accepted_total", "legendFormat": "Заказы приняты" },
    { "expr": "pvz_orders_delivered_total", "legendFormat": "Заказы доставлены" },
    { "expr": "pvz_orders_returned_total", "legendFormat": "Заказы возвращены" },
    {
     "expr": "pvz_orders_returned_to_courier_total",
     "legendFormat": "Заказы возвращены курьеру"
    }
   ]
  },
  {
   "title": "Время обработки заказа",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Время" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(pvz_order_processing_seconds_bucket[5m])) by (le))",
     "legendFormat": "95й процентиль"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(pvz_order_processing_seconds_bucket[5m])) by (le))",
     "legendFormat": "Медиана"
    }
   ]
  },
  {
   "title": "RPS по эндпоинтам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps", "label": "Запросов в секунду" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Код ответа HTTP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps", "label": "Запросов в секунду" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"2..\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Время ответа API (95-й процентиль)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s", "label": "Время ответа" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Статистика заказов",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pvz_orders_delivered_total", "legendFormat": "Доставлено" },
    { "expr": "pvz_orders_returned_total", "legendFormat": "Возвращено клиентом" },
    {
     "expr": "pvz_orders_returned_to_courier_total",
     "legendFormat": "Возвращено курьеру"
    }
   ]
  }
 ]
}